:toc:
:toclevels: 2
:toc: preamble

= Простое серверное приложение

Серверное приложение запускается на стороне сервера и ждёт от клиента запрос. Приложение крутится в бесконечном цикле - ждёт запроса, после получения обрабатывает его и посылает соответсвующий ответ клиенту в виде **htlm-страницы**, **json-файла** и т.п.


== API

Программный интерфейс приложения - совокупность правил (видов запросов), выполненных по стандарту, которые это приложение поддерживает.

Например:

- GET-запрос - позволяет получить что-то от сервера
- POST-запрос - позволяет передать что-то на сервер

Запрос выглядит просто как строка - http-адрес.
В строке адреса можно передать дополнительные параметры, например:

== Создаём справочник

- Пользователь посылает запрос через адресную строку браузера.  
- Приложение выводит на экран html-страницу.  
- Данные хранятся в json-файле.  
- Будем делать только GET-запросы (json-файл пользователь не будет менять).  

---  

=== Формат json

Объект, массив, как прочитать, как отобразить.  

=== http, https, express

Создание сервера и обработка событий.  
Как остановить сервер.  
mimeTypes.  

=== txt/plain

Приём запроса, обаботка, ответ.

=== html

Чтение, адаптация html, отправка клиенту.  

=== ico

== Обсудим задание на Лабу

---  
