:toc:
:toclevels: 2
:toc: preamble

= Простое серверное приложение

Серверное приложение запускается на стороне сервера и ждёт от клиента запрос. Приложение крутится в бесконечном цикле - ждёт запроса, после получения обрабатывает его и посылает соответсвующий ответ клиенту в виде **htlm-страницы**, **json-файла** и т.п.


== API

Программный интерфейс приложения - совокупность правил (видов запросов), выполненных по стандарту, которые это приложение поддерживает.

Например:

- GET-запрос - позволяет получить что-то от сервера
- POST-запрос - позволяет передать что-то на сервер

Запрос выглядит просто как строка - http-адрес.
В строке адреса можно передать дополнительные параметры, например:  

```js
http://localhost:3000/getByNumber?number=23  
http://localhost:3000/sortBy?direct=desc  
http://localhost:3000/sortBy?field=id&direct=asc  

```

== Создаём справочник

- Пользователь посылает запрос через адресную строку браузера.  
- Приложение выводит на экран html-страницу.  
- Данные хранятся в json-файле.  
- Будем делать только GET-запросы (json-файл пользователь не будет менять).  

---  

=== Формат json

Объект, массив, как прочитать, как отобразить.  

=== http, https, express

Создание сервера и обработка событий.  
Как остановить сервер.  
mimeTypes.  

=== html

Приём запроса, обаботка, ответ.  
Чтение html, адаптация html, отправка клиенту.  

=== ico

Браузер автоматически делает дополнительный запрос на иконку, кроме собственно запроса пользователя.  
Поэтому добавим в приложение обработку запроса на загрузку иконки.  

== Обсудим задание на Курсовой проект

---  
